<a href="https://colab.research.google.com/github/arunima-adhikary7/Twitter-Sentiment-Analysis-using-ML/blob/main/Twitter_Sentiment_Analysis_using_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!export KAGGLE_API_TOKEN=KGAT_ba37f53065fabcee0c02d23ea39d7bec

In [3]:
mkdir -p ~/.kaggle && echo KGAT_ba37f53065fabcee0c02d23ea39d7bec > ~/.kaggle/access_token && chmod 600 ~/.kaggle/access_token

In [5]:
!kaggle competitions list

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                                           deadline             category         reward  teamCount  userHasEntered
----------------------------------------------------------------------------  -------------------  --------  -------------  ---------  --------------
https://www.kaggle.com/competitions/passenger-screening-algorithm-challenge   2017-12-15 23:59:00  Featured  1,500,000 Usd        518           False
https://www.kaggle.com/competitions/zillow-prize-1                            2018-01-10 15:59:00  Featured  1,200,000 Usd       3770           False
https://www.kaggle.com/competitions/data-science-bowl-2017                    2017-04-12 23:59:00  Featured  1,000,000 Usd       1972           False
https://www.kaggle.com/competitions/vesuvius-challenge-ink-detection          2023-06-14 23:59:00  Featured  1,000,000 Usd       1249           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-3                  2026-11-02 23:59:00  Featured    850,000 Usd       2517           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-2                  2026-11-02 23:59:00  Featured    700,000 Usd       1617           False
https://www.kaggle.com/competitions/gemini-3                                  2025-12-12 23:59:00  Featured    500,000 Usd       4084           False
https://www.kaggle.com/competitions/openai-gpt-oss-20b-red-teaming            2025-08-26 23:59:00  Featured    500,000 Usd        601           False
https://www.kaggle.com/competitions/openai-to-z-challenge                     2025-06-29 23:59:00  Featured    500,000 Usd        225           False
https://www.kaggle.com/competitions/arc-prize-2026-paper-track                2026-11-09 23:59:00  Featured    450,000 Usd        150           False
https://www.kaggle.com/competitions/pokemon-tcg-ai-battle-challenge-strategy  2026-09-13 23:59:00  Featured    240,000 Usd        498           False
https://www.kaggle.com/competitions/llm-prompt-recovery                       2024-04-16 23:59:00  Featured    200,000 Usd       2175           False
https://www.kaggle.com/competitions/vesuvius-challenge-surface-detection      2026-02-27 23:59:00  Research    200,000 Usd       1391           False
https://www.kaggle.com/competitions/asl-fingerspelling                        2023-08-24 23:59:00  Research    200,000 Usd       1314           False
https://www.kaggle.com/competitions/second-annual-data-science-bowl           2016-03-14 23:59:00  Featured    200,000 Usd        192           False
https://www.kaggle.com/competitions/gemma-4-good-hackathon                    2026-05-18 23:59:00  Featured    200,000 Usd       1608           False
https://www.kaggle.com/competitions/kaggle-measuring-agi                      2026-04-16 23:59:00  Featured    200,000 Usd       1063           False
https://www.kaggle.com/competitions/datasciencebowl                           2015-03-16 23:59:00  Featured    175,000 Usd       1049           False
https://www.kaggle.com/competitions/data-science-bowl-2019                    2020-01-22 23:59:00  Featured    160,000 Usd       3493           False
https://www.kaggle.com/competitions/feedback-prize-2021                       2022-03-15 23:59:00  Featured    160,000 Usd       2058           False

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import warnings
warnings.filterwarnings("ignore")

In [25]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
# For the 'kazanova/sentiment140' dataset, a common file is 'training.1600000.processed.noemoticon.csv'
file_path = "training.1600000.processed.noemoticon.csv"

# Load the latest version, specifying no header and latin1 encoding
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "kazanova/sentiment140",
  file_path,
  pandas_kwargs={"encoding": "latin1", "header": None}
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records before column naming:")
display(df.head())

Using Colab cache for faster access to the 'sentiment140' dataset.
First 5 records before column naming:

,0,1,2,3,4,5
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [12]:
df

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
...,...,...,...,...,...,...
1599994,4,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599995,4,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599996,4,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599997,4,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599998,4,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [16]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [17]:
#printing the stopwords in english
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

Data processing

In [18]:
#checking no of rows and columns
df.shape

(1599999, 6)

In [19]:
df.head()

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [26]:
# naming the columns
column_names=['target','id','date','flag','user','text']
df.columns = column_names

# Displaying the first 5 rows again to confirm new column names and row count
print("First 5 records after column naming:")
display(df.head())

First 5 records after column naming:

,target,id,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [23]:
display(df.head())

,target,id,date,flag,user,text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [27]:
print(f"DataFrame shape: {df.shape}")

DataFrame shape: (1600000, 6)

In [30]:
# Checking the distribution of the target variable
df['target'].value_counts()

target
0    800000
4    800000
Name: count, dtype: int64

In [28]:
# Checking for missing values
df.isnull().sum()

target    0
id        0
date      0
flag      0
user      0
text      0
dtype: int64

convert the target '4' to '1'

In [31]:
df.replace({'target':{4:1}},inplace=True)

In [32]:
# Checking the distribution of the target variable again
df['target'].value_counts()

target
0    800000
1    800000
Name: count, dtype: int64

0---> Negative tweet
1---> positive tweet

**Stemming**

Stemming is the process of reducing a word to its root word

Example:actor,actress,acting=act

In [33]:
port_stem=PorterStemmer()

In [34]:
def stemming(content):
  stemmed_content=re.sub('[^a-zA-Z]',' ',content)
  stemmed_content=stemmed_content.lower()
  stemmed_content=stemmed_content.split()
  stemmed_content=[port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content=' '.join(stemmed_content)
  return stemmed_content

In [ ]:
df['stemmed_content']=df['text'].apply(stemming)